In [28]:
import pandas as pd 
import tkinter as tk
import time
import statistics
import numpy as np

from tkinter import filedialog
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [5]:
#Get file Path
root = tk.Tk()
root.withdraw()
file_path = filedialog.askopenfilename()

In [22]:
df = pd.read_csv(r'{}'.format(file_path))
a = len(df.columns)- 1
X = df.iloc[:,:a].values
y = df.iloc[:,a].values

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [24]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(y_pred)
    print("\n\nNumber of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
    return model.score(X_test, y_test)

In [25]:
def skfd(model, X_train, X_test, y_train, y_test):
    stratikfold = str(input('Do you wanna perform StratifiedKFold?\n'))
    stratikfold =  stratikfold.upper()
    
    while(stratikfold != 'YES' and  stratikfold != 'NO'):
        print('Invalid Choice!!! 😒')
        time.sleep(1)
        stratikfold = str(input('Do you wanna perform StratifiedKFold?\n'))
        stratikfold =  stratikfold.upper()
    
    if( stratikfold == 'YES'):
        n_splits = int(input('Enter the number of splits for StratifiedKFold:\n'))
        folds = StratifiedKFold(n_splits)
        scores_rf = []
        for train_index, test_index in folds.split(X,y):
            X_train, X_test, y_train, y_test = X[train_index], X[test_index],y[train_index], y[test_index]
            scores_rf.append(get_score(model, X_train, X_test, y_train, y_test))
            print(statistics.mean(scores_rf))
    else:
        print('Good Luck!!! 🤞')
    return 0

In [26]:
def classification():
    choice = int(input('Select any number from below:\n1. KNearestNeighbor\n2. DecisionTree\n3. MultilayerPerceptron\n4. NaiveBayesClassifier\n5. RandomForestClassifier\n6. XGBoost\n7. SupportVectorMachine\n\n'))
    while(choice < 1 or choice > 7):
        print('Invalid Choice!!! 😒')
        time.sleep(1)
        choice = int(input('Select any number from below:\n1. KNearestNeighbor\n2. DecisionTree\n3. MultilayerPerceptron\n4. NaiveBayesClassifier\n5. RandomForestClassifier\n6. XGBoost\n7. SupportVectorMachine\n\n'))
    if(choice == 1):
        print('You have selected KNN! 🤞\n')
        time.sleep(0.5)
        from sklearn.neighbors import KNeighborsClassifier
        n_neighbors = int(input('Enter the number of nearest neighbors\n'))
        print('accuracy:',get_score(KNeighborsClassifier(n_neighbors), X_train, X_test, y_train, y_test))
        skfd(KNeighborsClassifier(n_neighbors), X_train, X_test, y_train, y_test)
        
    elif(choice == 2):
        print('You have Selected DT! 🤞\n')
        time.sleep(0.5)
        from sklearn import tree
        print('accuracy:',get_score(tree.DecisionTreeClassifier(), X_train, X_test, y_train, y_test))
        skfd(tree.DecisionTreeClassifier(), X_train, X_test, y_train, y_test)
    elif(choice == 3):
        print('You have selected MLP! 🤞\n')
        time.sleep(0.5)
        from sklearn.neural_network import MLPClassifier
        print('accuracy:',get_score(MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1), X_train, X_test, y_train, y_test))
        skfd(MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1), X_train, X_test, y_train, y_test)
    elif(choice == 4):
        print('You have selected NBC! 🤞\n')
        time.sleep(0.5)
        from sklearn.naive_bayes import GaussianNB
        print('accuracy:',get_score(GaussianNB(), X_train, X_test, y_train, y_test))
        skfd(GaussianNB(), X_train, X_test, y_train, y_test)
    elif(choice == 5):
        print('You have selected RFC! 🤞\n')
        time.sleep(0.5)
        from sklearn.ensemble import RandomForestClassifier
        print('accuracy:',get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
        skfd(RandomForestClassifier(), X_train, X_test, y_train, y_test)
        
    elif(choice == 6):
        print('You have selected XBG! 🤞\n')
        time.sleep(0.5)
        import xgboost
        print('accuracy:',get_score(xgboost.XGBClassifier(), X_train, X_test, y_train, y_test))
        skfd(xgboost.XGBClassifier(), X_train, X_test, y_train, y_test)
    elif(choice == 7):
        print('You have selected SVM! 🤞\n')
        time.sleep(0.5)
        from sklearn import svm
        print('accuracy:',get_score(svm.SVC(), X_train, X_test, y_train, y_test))
        skfd(svm.SVC(), X_train, X_test, y_train, y_test)

In [27]:
classification()

Select any number from below:
1. KNearestNeighbor
2. DecisionTree
3. MultilayerPerceptron
4. NaiveBayesClassifier
5. RandomForestClassifier
6. XGBoost
7. SupportVectorMachine

5
You have selected RFC! 🤞

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'I